version: '3'

services:
  maestro-studio:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILDPLATFORM=${BUILDPLATFORM:-linux/$(uname -m)}
        - TARGETPLATFORM=${TARGETPLATFORM:-linux/$(uname -m)}
    ports:
      - "8000:8000"
    environment:
      - JAVA_OPTS=-Xmx512m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped